<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lydg</string>
	</array>
	<key>name</key>
	<string>Lydrige</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(def)\s*\n*\.(\w+)\s*\n*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variable Define</string>
			<key>end</key>
			<string>\s*\n*;$\s*\n*</string>
			<key>name</key>
			<string>meta.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>#(.)*$</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\s*\n*(\w*)\s*\n*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>S-Expressions</string>
			<key>end</key>
			<string>\s*\n*\)</string>
			<key>name</key>
			<string>meta.*</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(\w*)\s*\n*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Statements</string>
			<key>end</key>
			<string>\s*\n*;</string>
			<key>name</key>
			<string>meta.*</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Builtin Types</string>
			<key>match</key>
			<string>\b(any|int|float|double|char|string|qexpr|func)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Integers, Floats, Hex, and Binary</string>
			<key>match</key>
			<string>\b(-?[0-9]+\.[0-9]+|-?[0-9]+|0x[0-9A-Fa-f]+|0b[0-1]+)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Character Literal</string>
			<key>match</key>
			<string>'(\\.|[^'])'</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String Literal</string>
			<key>match</key>
			<string>"(\\.|[^"])*"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators</string>
			<key>match</key>
			<string>\b(\+|\-|\*|\/|%|\^|==|!=)\b</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control Flow</string>
			<key>match</key>
			<string>\b(if)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lydrige</string>
	<key>uuid</key>
	<string>01c739bd-bc3c-4cf5-94a8-f9b7ed9c002d</string>
</dict>
</plist>
