<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lydg</string>
	</array>
	<key>name</key>
	<string>Lydrige</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string></string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b-?[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.lydrige</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b-?[0-9]+\.[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.lydrige</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0x[0-9a-fA-F][0-9a-fA-F]\b</string>
			<key>name</key>
			<string>constant.numeric.lydrige</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ok|nil|true|false)\b</string>
			<key>name</key>
			<string>constant.language.lydrige</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Tab stops like $1, $2...</string>
			<key>match</key>
			<string>\b(list|first|last|head|tail|eval|inner_eval|join|len|get|extract|set|typeof|throw|to_list|to_qexpr|read|def|const|let|lambda|==|!=|&gt;|&lt;|&gt;=|&lt;=|!|and|or|print|error|load)\b</string>
			<key>name</key>
			<string>support.function.lydrige</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\+|-|\*|/|%|\^)\b</string>
			<key>name</key>
			<string>keyword.operator.lydrige</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|while|exit)\b</string>
			<key>name</key>
			<string>keyword.control.lydrige</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(int|double|byte|string|char|err|qexpr|func|any|lst)\b</string>
			<key>name</key>
			<string>storage.type.lydrige</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>constant.character.lydrige</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#[^\r\n]*</string>
			<key>name</key>
			<string>comment.number-sign.lydrige</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.lydrige</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lydrige</string>
	<key>uuid</key>
	<string>7471ea4f-694f-47e8-b834-20bfa13f270a</string>
</dict>
</plist>
